version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: engagesyncdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: rushikesh855/engagesync-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: engagesyncdb
      DB_HOST: db
      DB_PORT: 5432
      DB_SSLMODE: disable

volumes:
  postgres-data: