version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: engagesyncdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
      - ./wait-for:/wait-for
    entrypoint: ["/wait-for", "db:5432", "--", "migrate"]
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://postgres:root@db:5432/engagesyncdb?sslmode=disable",
        "up"
      ]

  app:
    build: .
    depends_on:
      - db
      - migrate
    environment:
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: engagesyncdb
      DB_SSLMODE: disable
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8080:8080"
    command: ["./engagesync"]

volumes:
  pgdata:
